### ISSUE TITLE
Wikitext103 Download Link Fix Plus and Script Enhancements 

### ISSUE THREAD

**Issue by gkielian** [ReaLLMASIC/nanoGPT#86]
The main link seems to be down since last week, creating an issue to track.

Also let's aim to add progress bar too, and double check we're using the raw wikitext link (the main one apparently comes with  <unk> tokens for masking tasks).

**Comment by gkielian** [comment]
@klei22 Could you take a look into the download scripts?

**Comment by klei22** [comment]
https://github.com/ReaLLMASIC/nanoGPT/pull/87
